create table bookmarks(
  id INTEGER primary key generated by default as identity,
  title TEXT NOT NULL,
  url_name TEXT NOT NULL,
  created TIMESTAMP default NOW(),
  rating INTEGER,
  url_desc TEXT
);